# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Option', verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '打分(1-10分)'), (2, '单选'), (3, '建议')], verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='cls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ClassList', verbose_name='所属班级'),
        ),
    ]
